name: Tests

on:
    push:
        branches: [ development, main ]
    pull_request:
        branches: [ development ]

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v2
            -   name: Set up JDK
                uses: actions/setup-java@v2
                with:
                    java-version: '17'
                    distribution: 'adopt'
            -   name: Build with Maven
                run: mvn verify
